setup: &setup
  adapter: sqlite3
  encoding: utf8
  host: localhost
  pool: 5

development:
  <<: *setup
  database: db/development.sqlite3

test:
  <<: *setup
  database: db/test.sqlite3

staging:
  <<: *setup
  database: db/staging.sqlite3

production:
  <<: *setup
  database: db/production.sqlite3

cucumber:
  <<: *test